[PREP]
labelset = "range: 1-27"
spect_format = "mat"
data_dir = "D:\\YardenBirds\\llb11\\annotated"
output_dir = "D:\\YardenBirds\\llb11\\train"

[SPECT_PARAMS]
fft_size = 1024
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25

[DATALOADER]
window_size = 370

[TRAIN]
models = "TweetyNet"
normalize_spectrograms = false
batch_size = 8
num_epochs = 1
val_step = 5000
ckpt_step = 10000
num_workers = 16
device = "cuda"
root_results_dir = "C:\\Users\\Yarden Cohen\\repos\\tweetynet\\doc\\notebooks\\Canary_Example_Train_Predict\\results"
csv_path = "C:\\Users\\Yarden Cohen\\repos\\tweetynet\\doc\\notebooks\\Canary_Example_Train_Predict\\annotated_prep_llb11_example.csv"

[TweetyNet.optimizer]
lr = 0.001
