[PREP]
labelset = "iabcdefghjk"
data_dir = "D:\\BengaleseFinches\\gy6or6\\032212"
output_dir = "C:\\Users\\Yarden Cohen\\repos\\tweetynet\\doc\\notebooks\\BF_Example_Train_Predict"
train_dur = 180
val_dur = 80
test_dur = 200
audio_format = "cbin"
annot_format = "notmat"

[SPECT_PARAMS]
fft_size = 512
step_size = 64
freq_cutoffs = [ 500, 10000,]
thresh = 6.25
transform_type = "log_spect"

[DATALOADER]
window_size = 88

[TRAIN]
normalize_spectrograms = true
num_epochs = 5
batch_size = 8
val_step = 50
ckpt_step = 200
patience = 4
models = [ "TweetyNet",]
root_results_dir = "C:\\Users\\Yarden Cohen\\repos\\tweetynet\\doc\\notebooks\\BF_Example_Train_Predict"
num_workers = 16
device = "cuda"
csv_path = "C:\\Users\\Yarden Cohen\\repos\\tweetynet\\doc\\notebooks\\BF_Example_Train_Predict\\gy6or6_032212_example_prep.csv"

[TweetyNet.optimizer]
lr = 0.001
